/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coreSidebar: [{ type: 'autogenerated', dirName: 'core' }],
  stylesSidebar: [{ type: 'autogenerated', dirName: 'styles' }],
  contentSidebar: [{ type: 'autogenerated', dirName: 'content' }],
  assetsSidebar: [{ type: 'autogenerated', dirName: 'assets' }],
  componentsSidebar: [{ type: 'autogenerated', dirName: 'components' }],
  patternsSidebar: [{ type: 'autogenerated', dirName: 'patterns' }],
};

module.exports = sidebars;
