/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  getStartedSidebar: [{ type: 'autogenerated', dirName: 'get-started' }],
  stylesSidebar: [{ type: 'autogenerated', dirName: 'styles' }],
  uxcontentSidebar: [{ type: 'autogenerated', dirName: 'ux-writing' }],
  assetsSidebar: [{ type: 'autogenerated', dirName: 'assets' }],
  componentsSidebar: [{ type: 'autogenerated', dirName: 'components' }],
  patternsSidebar: [{ type: 'autogenerated', dirName: 'patterns' }],
  recipesSidebar: [{ type: 'autogenerated', dirName: 'recipes' }],
};

module.exports = sidebars;
