name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: deploy-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        env:
          NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache .docusaurus Directory
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-cache-docusaurus-main
          restore-keys: ${{ runner.os }}-cache-docusaurus-main

      - name: Cache build Directory
        uses: actions/cache@v3
        with:
          path: public
          key: ${{ runner.os }}-public-docusaurus-main
          restore-keys: ${{ runner.os }}-public-docusaurus-main

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_S3_BUCKET_REGION }}

      - name: Deploy AWS
        uses: reggionick/s3-deploy@338f242d6f2aaad0db698d66dffe836a7629b160
        with:
          folder: build
          bucket: ${{ secrets.AWS_S3_BUCKET_PROD }}
          bucket-region: ${{ secrets.AWS_S3_BUCKET_REGION }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"