name: Deploy Preview

on:
  push:
    branches: [gh-pages]  # preview builds happen when gh-pages is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout preview branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build preview site
        run: npm run build

      - name: Deploy preview site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview  # 👈 this creates a subfolder on the gh-pages branch
          keep_files: true
