name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: deploy-pr-preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        if: github.event.action != 'closed'
        run: npm ci

      - name: Build
        if: github.event.action != 'closed'
        run: npm run build

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build
          token: ${{ secrets.GITHUB_TOKEN }}
